# ────────────────────────────────────────────────────────────────
#  Pre‑commit hooks for agent‑generator
#  Run `pre-commit install` after cloning.
# ────────────────────────────────────────────────────────────────
repos:
  # ---------------- Code formatting ----------------
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix]

  # -------------- Import sorting ------------------
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # -------------- Static typing -------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]

  # -------------- Basic hygiene -------
