"""Build service: take a validated ProjectSpec and produce generated files."""
from __future__ import annotations

import ast
from typing import Any

from agent_generator.config import Settings, get_settings_lenient
from agent_generator.domain.project_spec import ProjectSpec
from agent_generator.domain.artifact_bundle import ArtifactBundle, GeneratedFile, ValidationIssue
from agent_generator.frameworks import FRAMEWORKS


def _spec_to_mermaid(spec: ProjectSpec) -> str:
    """Generate a Mermaid diagram directly from a ProjectSpec (no Workflow needed)."""
    lines = ["graph TD"]
    for t in spec.tasks:
        label = t.description[:60].replace('"', "'")
        lines.append(f'    {t.id}["{label}"]')
    for t in spec.tasks:
        for dep in t.depends_on:
            lines.append(f"    {dep} --> {t.id}")
    return "\n".join(lines)


def build(
    spec: ProjectSpec,
    mcp: bool = False,
) -> ArtifactBundle:
    """Build a project from a validated ProjectSpec.

    Returns an ArtifactBundle with generated files, manifest, warnings, and errors.
    """
    from agent_generator.application.validation_service import validate_artifact

    framework_name = spec.framework.value
    if framework_name not in FRAMEWORKS:
        framework_name = "crewai"

    settings = get_settings_lenient()

    # Generate code directly from spec (no Workflow adapter)
    generator = FRAMEWORKS[framework_name]()
    code = generator.generate_from_spec(spec, settings, mcp=mcp or spec.runtime.mcp_wrapper)
    diagram = _spec_to_mermaid(spec)

    # Build file list
    project_name = spec.name
    generated_files: list[GeneratedFile] = []

    ext = generator.file_extension
    if ext == "yaml":
        generated_files.append(GeneratedFile(
            path=f"{project_name}.yaml",
            content=code,
            language="yaml",
        ))
    else:
        generated_files.append(GeneratedFile(
            path=f"src/{project_name}/main.py",
            content=code,
            language="python",
        ))
        generated_files.append(GeneratedFile(
            path=f"src/{project_name}/__init__.py",
            content=f'"""Generated {project_name} package."""\n',
            language="python",
        ))

    generated_files.append(GeneratedFile(
        path="README.md",
        content=(
            f"# {project_name}\n\n{spec.description}\n\n"
            f"Framework: {framework_name}\n"
            f"Tier: {spec.template_tier.value}\n\n"
            f"Generated by [agent-generator](https://github.com/ruslanmv/agent-generator).\n"
        ),
        language="markdown",
    ))

    # Generate requirements.txt for Python projects
    if ext == "py":
        deps = ["pydantic>=2.0"]
        if framework_name in ("crewai", "crewai_flow"):
            deps.extend(["crewai>=1.12", "crewai-tools>=0.14"])
        elif framework_name == "langgraph":
            deps.extend(["langgraph>=1.1", "langchain-core>=0.1"])
        elif framework_name == "react":
            deps.append("requests>=2.31")
        generated_files.append(GeneratedFile(
            path="requirements.txt",
            content="\n".join(sorted(set(deps))) + "\n",
            language="text",
        ))

    # Syntax validation
    errors: list[ValidationIssue] = []
    warnings: list[ValidationIssue] = []
    for f in generated_files:
        if f.path.endswith(".py"):
            try:
                ast.parse(f.content)
            except SyntaxError as e:
                errors.append(ValidationIssue(
                    level="error",
                    message=f"{f.path}: Syntax error line {e.lineno}: {e.msg}",
                ))

    # Build manifest
    manifest: dict[str, Any] = {
        "framework": framework_name,
        "diagram": diagram,
        "generator_version": "0.2.1",
        "project_name": project_name,
        "template_tier": spec.template_tier.value,
    }

    artifact = ArtifactBundle(
        files=generated_files,
        manifest=manifest,
        warnings=warnings,
        errors=errors,
    )

    # Run security validation
    artifact = validate_artifact(artifact)

    return artifact


def build_dict(spec: ProjectSpec, mcp: bool = False) -> dict[str, Any]:
    """Build and return a backward-compatible dict (for CLI/web)."""
    artifact = build(spec, mcp=mcp)
    return {
        "files": {f.path: f.content for f in artifact.files},
        "diagram": artifact.manifest.get("diagram", ""),
        "framework": artifact.manifest.get("framework", spec.framework.value),
        "warnings": [w.message for w in artifact.warnings],
        "errors": [e.message for e in artifact.errors],
        "spec": spec.model_dump(),
        "manifest": artifact.manifest,
        "valid": artifact.valid,
    }
