name: 📦 Build & Publish Docker Image on Release

# 1) Trigger on published releases
on:
  release:
    types: [published]
  workflow_dispatch:         # also allow manual runs

permissions:
  contents: read            # for checkout
  packages: write           # to push images

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 2) Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    # 3) Determine version from the release event
    - name: Set up version
      run: |
        echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      # For 'release' events, GITHUB_REF is refs/tags/<tag_name>

    # 4) Log in to Docker Hub
    - name: Docker Hub login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 5) (Optional) QEMU for multi‑arch
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # 6) Build & push the image with both tags
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-creator:latest
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-creator:${{ env.RELEASE_TAG }}

    # 7) Verify
    - name: Verify pushed image
      run: |
        docker pull docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-creator:${{ env.RELEASE_TAG }}
        docker images docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-creator
