name: 📦 Build & Publish to Docker Hub

on:
  push:
    branches: [ main ]
    # You can also add tags: [ 'v*.*.*' ]

permissions:
  contents: read    # for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. (Optional) QEMU for multi‑arch
      - uses: docker/setup-qemu-action@v2

      # 3. Build & push
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-creator:latest
            # Optionally tag by git tag:
            # docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-creator:${{ github.ref_name }}
